function policy = zmdpPolicyParse(filename)
%  eg. [maxValue action] = zmdpParse(filename,belief)
% 
% filename: is the name of the file output generated by zmdpSolver usually
% out.policy. 
% belief  : a (1,n) vector with the probability belief of states where n is
% the number of states in the POMDP model. 

file = textread(filename,'%s','delimiter','\n','whitespace',' \b\t','bufsize',8000000);

% remove comments and empty lines (if they exist)
k=0;
for i=1:length(file)
  comment=strfind(file{i},'#');
  if ~isempty(comment)
    file{i}(comment(1):end)=[];
  end
  if ~isempty(file{i})
    k=k+1;
    fileTemp{k}=file{i};
  end
%   if (mod(i,1000)==0)
%       display(i);
%   end
end
clear file;

% remove un-necessary info
k=0;
for i=1:length(fileTemp)
  leftCurlyBracket =strfind(fileTemp{i},'{');
  rightCurlyBracket=strfind(fileTemp{i},'}');
  leftBracket =strfind(fileTemp{i},'[');
  rightBracket=strfind(fileTemp{i},']'); 
  policy = strfind(fileTemp{i},'policyType');
  planes = strfind(fileTemp{i},'planes');
  entries = strfind(fileTemp{i},'entries');
  if isempty(leftCurlyBracket) && isempty(rightCurlyBracket) && isempty(leftBracket) && isempty(rightBracket) && isempty(planes) && isempty(policy)&& isempty(entries)
    k=k+1;
    file{k}=fileTemp{i};
  end
end
clear fileTemp;

for i=1:length(file)
  % remove right Arrows
  rightArrow =strfind(file{i},'=>');
  if ~isempty(rightArrow)
      file{i}(rightArrow(1):rightArrow(1)+1)=[];
  end 
  % remove the commas
  comma =strfind(file{i},',');
  s = length(comma);
  if ~isempty(comma)
      for j=0:(length(comma)-1)
          file{i}((comma(j+1)-j):(comma(j+1)-j))=[];
      end
  end
end

nrLines=length(file);
k=1;
policy.numPlanes = sscanf(file{k},'%*s %d');

k=k+1;
for i=1:policy.numPlanes
    policy.planeActions(i) = sscanf(file{k},'%*s %d');
    k=k+1;
    [numEntries] = sscanf(file{k},'%*s %d');
    k=k+1;
    for j=1:numEntries
        x = sscanf(file{k},'%d %f');
        policy.planeEntries{i,(x(1)+1)} = x(2);
        k=k+1;
    end
end

end