/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menu4;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem5;
  GtkWidget *menu5;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *menuitem6;
  GtkWidget *menu6;
  GtkWidget *menuitem7;
  GtkWidget *menu7;
  GtkWidget *about1;
  GtkWidget *hbox1;
  GtkWidget *frame1;
  GtkWidget *alignment4;
  GtkWidget *vbox5;
  GtkWidget *drawingarea1;
  GtkWidget *notebook;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview1;
  GtkWidget *label36;
  GtkWidget *empty_notebook_page;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label12;
  GtkWidget *frame2;
  GtkWidget *alignment5;
  GtkWidget *fixed2;
  GtkWidget *frame7;
  GtkWidget *vbox2;
  GtkWidget *hbox5;
  GtkWidget *hbox7;
  GtkWidget *label1;
  GtkWidget *entry1;
  GtkWidget *label2;
  GtkWidget *entry2;
  GtkWidget *label3;
  GtkWidget *entry3;
  GtkWidget *hbox6;
  GtkWidget *hbox8;
  GtkWidget *startx;
  GtkWidget *starty;
  GtkWidget *start_theta;
  GtkWidget *label15;
  GtkWidget *frame8;
  GtkWidget *vbox3;
  GtkWidget *hbox10;
  GtkWidget *label4;
  GtkWidget *entry4;
  GtkWidget *label5;
  GtkWidget *entry5;
  GtkWidget *label6;
  GtkWidget *entry6;
  GtkWidget *hbox11;
  GtkWidget *targetx;
  GtkWidget *targety;
  GtkWidget *target_theta;
  GtkWidget *label20;
  GtkWidget *frame9;
  GtkWidget *alignment9;
  GtkWidget *vbox4;
  GtkWidget *hbox12;
  GtkWidget *label31;
  GtkWidget *pixel_size;
  GtkWidget *label32;
  GtkWidget *pixels_per_tile;
  GtkWidget *hbox15;
  GtkWidget *label33;
  GtkWidget *reg_grid_dist;
  GtkWidget *label34;
  GtkWidget *nodes_connection_radius;
  GtkWidget *hbox14;
  GtkWidget *label35;
  GtkWidget *obstacle_radius;
  GtkWidget *hbox21;
  GtkWidget *label46;
  GtkWidget *bridge_length;
  GtkWidget *label27;
  GtkWidget *frame10;
  GtkWidget *alignment10;
  GtkWidget *vbox6;
  GtkWidget *hbox16;
  GtkWidget *label40;
  GtkWidget *k_distance;
  GtkWidget *label41;
  GtkWidget *k_theta;
  GtkWidget *hbox17;
  GtkWidget *label42;
  GtkWidget *tracking_distance;
  GtkWidget *hbox18;
  GtkWidget *label43;
  GtkWidget *Linea_speed;
  GtkWidget *hbox19;
  GtkWidget *label44;
  GtkWidget *hbox20;
  GtkWidget *label45;
  GtkWidget *safety_distance;
  GtkWidget *label39;
  GtkWidget *follow_path;
  GtkWidget *stop_following;
  GtkWidget *connect_to_player;
  GtkWidget *path_plan;
  GtkWidget *frame11;
  GtkWidget *alignment11;
  GtkWidget *fixed3;
  GtkWidget *simulate_radio;
  GSList *simulate_radio_group = NULL;
  GtkWidget *wheelchair_radio;
  GtkWidget *label47;
  GtkWidget *generate_cspace;
  GtkWidget *label13;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  GTK_WIDGET_SET_FLAGS (window1, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (window1, GTK_CAN_DEFAULT);
  gtk_widget_set_events (window1, GDK_EXPOSURE_MASK);
  gtk_window_set_title (GTK_WINDOW (window1), "                                                                                                         WheelChair Navigation Panel");
  gtk_window_set_modal (GTK_WINDOW (window1), TRUE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (window1), TRUE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menu4 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menu4);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menu4), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menu4), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menu4), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menu4), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu4), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menu4), quit1);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem5);

  menu5 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menu5);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menu5), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menu5), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menu5), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menu5), delete1);

  menuitem6 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem6);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem6);

  menu6 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem6), menu6);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menu7 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menu7);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menu7), about1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox1), frame1, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_IN);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (frame1), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 0, 0, 12, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (alignment4), vbox5);

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea1);
  gtk_box_pack_start (GTK_BOX (vbox5), drawingarea1, TRUE, TRUE, 0);
  gtk_widget_set_events (drawingarea1, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON3_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_FOCUS_CHANGE_MASK);

  notebook = gtk_notebook_new ();
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (vbox5), notebook, TRUE, TRUE, 0);
  gtk_widget_set_size_request (notebook, -1, 250);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook), scrolledwindow3);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview1);

  label36 = gtk_label_new (_("OutPut"));
  gtk_widget_show (label36);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), label36);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook), empty_notebook_page);

  label37 = gtk_label_new (_("Logs"));
  gtk_widget_show (label37);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), label37);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook), empty_notebook_page);

  label38 = gtk_label_new (_("Other Contron Options"));
  gtk_widget_show (label38);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 2), label38);

  label12 = gtk_label_new (_("<b>Map View</b>"));
  gtk_widget_show (label12);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label12);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox1), frame2, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_ETCHED_OUT);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (frame2), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 12, 0);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (alignment5), fixed2);
  gtk_widget_set_size_request (fixed2, 250, -1);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_fixed_put (GTK_FIXED (fixed2), frame7, 0, 16);
  gtk_widget_set_size_request (frame7, 248, 72);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame7), vbox2);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox5, TRUE, TRUE, 0);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (hbox5), hbox7, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("X(m):"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox7), label1, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox7), entry1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry1, -1, 18);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("0"));

  label2 = gtk_label_new (_("Y(m):"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox7), label2, FALSE, FALSE, 0);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_box_pack_start (GTK_BOX (hbox7), entry2, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry2, -1, 18);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("0"));

  label3 = gtk_label_new (_("T(deg):"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox7), label3, FALSE, FALSE, 0);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_box_pack_start (GTK_BOX (hbox7), entry3, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry3, -1, 18);
  gtk_entry_set_text (GTK_ENTRY (entry3), _("180"));

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox6, TRUE, TRUE, 0);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (hbox6), hbox8, TRUE, TRUE, 0);

  startx = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -20, 20, 0.01, 0, 0)));
  gtk_widget_show (startx);
  gtk_box_pack_start (GTK_BOX (hbox8), startx, TRUE, TRUE, 0);

  starty = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -20, 20, 0.01, 0, 0)));
  gtk_widget_show (starty);
  gtk_box_pack_start (GTK_BOX (hbox8), starty, TRUE, TRUE, 0);

  start_theta = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -20, 20, 0.01, 0, 0)));
  gtk_widget_show (start_theta);
  gtk_box_pack_start (GTK_BOX (hbox8), start_theta, TRUE, TRUE, 0);

  label15 = gtk_label_new (_("<b>Start Location</b>"));
  gtk_widget_show (label15);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label15);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_fixed_put (GTK_FIXED (fixed2), frame8, 0, 96);
  gtk_widget_set_size_request (frame8, 248, 72);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame8), vbox3);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox10, TRUE, TRUE, 0);

  label4 = gtk_label_new (_("X(m):"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox10), label4, FALSE, FALSE, 0);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_box_pack_start (GTK_BOX (hbox10), entry4, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry4, -1, 18);
  gtk_entry_set_text (GTK_ENTRY (entry4), _("0"));

  label5 = gtk_label_new (_("Y(m):"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox10), label5, FALSE, FALSE, 0);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_box_pack_start (GTK_BOX (hbox10), entry5, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry5, -1, 18);
  gtk_entry_set_text (GTK_ENTRY (entry5), _("0"));

  label6 = gtk_label_new (_("T(deg):"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox10), label6, FALSE, FALSE, 0);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_box_pack_start (GTK_BOX (hbox10), entry6, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry6, -1, 18);
  gtk_entry_set_text (GTK_ENTRY (entry6), _("0"));

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox11, TRUE, TRUE, 0);

  targetx = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -20, 20, 0.01, 0, 0)));
  gtk_widget_show (targetx);
  gtk_box_pack_start (GTK_BOX (hbox11), targetx, TRUE, TRUE, 0);

  targety = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -20, 20, 0.01, 0, 0)));
  gtk_widget_show (targety);
  gtk_box_pack_start (GTK_BOX (hbox11), targety, TRUE, TRUE, 0);

  target_theta = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -20, 20, 0.01, 0, 0)));
  gtk_widget_show (target_theta);
  gtk_box_pack_start (GTK_BOX (hbox11), target_theta, TRUE, TRUE, 0);

  label20 = gtk_label_new (_("<b>Target Location</b>"));
  gtk_widget_show (label20);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label20);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_show (frame9);
  gtk_fixed_put (GTK_FIXED (fixed2), frame9, 0, 168);
  gtk_widget_set_size_request (frame9, 248, 136);

  alignment9 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (frame9), alignment9);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment9), 0, 0, 12, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (alignment9), vbox4);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox12, TRUE, TRUE, 0);

  label31 = gtk_label_new (_("Pixel Size(m):"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox12), label31, FALSE, FALSE, 0);

  pixel_size = gtk_entry_new ();
  gtk_widget_show (pixel_size);
  gtk_box_pack_start (GTK_BOX (hbox12), pixel_size, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (pixel_size), _("0.047"));

  label32 = gtk_label_new (_(" Pixels/Tile:"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox12), label32, FALSE, FALSE, 0);

  pixels_per_tile = gtk_entry_new ();
  gtk_widget_show (pixels_per_tile);
  gtk_box_pack_start (GTK_BOX (hbox12), pixels_per_tile, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (pixels_per_tile), _("1"));

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox15, TRUE, TRUE, 0);

  label33 = gtk_label_new (_("Reg Grid d(m):"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox15), label33, FALSE, FALSE, 0);

  reg_grid_dist = gtk_entry_new ();
  gtk_widget_show (reg_grid_dist);
  gtk_box_pack_start (GTK_BOX (hbox15), reg_grid_dist, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (reg_grid_dist), _("0.2"));

  label34 = gtk_label_new (_("Dist Nodes(m):"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox15), label34, FALSE, FALSE, 0);

  nodes_connection_radius = gtk_entry_new ();
  gtk_widget_show (nodes_connection_radius);
  gtk_box_pack_start (GTK_BOX (hbox15), nodes_connection_radius, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (nodes_connection_radius), _("0.5"));

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox14, TRUE, TRUE, 0);

  label35 = gtk_label_new (_("Obstacle Expansion Radius(m):"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox14), label35, FALSE, FALSE, 0);

  obstacle_radius = gtk_entry_new ();
  gtk_widget_show (obstacle_radius);
  gtk_box_pack_start (GTK_BOX (hbox14), obstacle_radius, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (obstacle_radius), _("0.2"));

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox21, TRUE, TRUE, 0);

  label46 = gtk_label_new (_("Bridge Test Length(m):"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox21), label46, FALSE, FALSE, 0);

  bridge_length = gtk_entry_new ();
  gtk_widget_show (bridge_length);
  gtk_box_pack_start (GTK_BOX (hbox21), bridge_length, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (bridge_length), _("2"));

  label27 = gtk_label_new (_("<b>Path Planning</b>"));
  gtk_widget_show (label27);
  gtk_frame_set_label_widget (GTK_FRAME (frame9), label27);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  frame10 = gtk_frame_new (NULL);
  gtk_widget_show (frame10);
  gtk_fixed_put (GTK_FIXED (fixed2), frame10, 0, 304);
  gtk_widget_set_size_request (frame10, 248, 150);

  alignment10 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (frame10), alignment10);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment10), 0, 0, 12, 0);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (alignment10), vbox6);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox16, TRUE, TRUE, 0);

  label40 = gtk_label_new (_("K-Distance:"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox16), label40, FALSE, FALSE, 0);

  k_distance = gtk_entry_new ();
  gtk_widget_show (k_distance);
  gtk_box_pack_start (GTK_BOX (hbox16), k_distance, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (k_distance), _("0.15"));

  label41 = gtk_label_new (_("  K-Theta:"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox16), label41, FALSE, FALSE, 0);

  k_theta = gtk_entry_new ();
  gtk_widget_show (k_theta);
  gtk_box_pack_start (GTK_BOX (hbox16), k_theta, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (k_theta), _("0.28"));

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox17, TRUE, TRUE, 0);

  label42 = gtk_label_new (_("Tracking Distance(m):"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox17), label42, FALSE, FALSE, 0);

  tracking_distance = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 4, 0.1, 0, 0)));
  gtk_widget_show (tracking_distance);
  gtk_box_pack_start (GTK_BOX (hbox17), tracking_distance, TRUE, TRUE, 0);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox18, TRUE, TRUE, 0);

  label43 = gtk_label_new (_("Linear Speed:"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox18), label43, FALSE, FALSE, 0);

  Linea_speed = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0.1, 0, 3, 0.01, 0, 0)));
  gtk_widget_show (Linea_speed);
  gtk_box_pack_start (GTK_BOX (hbox18), Linea_speed, TRUE, TRUE, 0);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox19, TRUE, TRUE, 0);

  label44 = gtk_label_new ("");
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox19), label44, FALSE, FALSE, 0);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_box_pack_start (GTK_BOX (hbox19), hbox20, TRUE, TRUE, 0);

  label45 = gtk_label_new (_("Safety Distance(m):"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox20), label45, FALSE, FALSE, 0);

  safety_distance = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0.1, 0, 1, 0.01, 0, 0)));
  gtk_widget_show (safety_distance);
  gtk_box_pack_start (GTK_BOX (hbox20), safety_distance, TRUE, TRUE, 0);

  label39 = gtk_label_new (_("<b>Path Following</b>"));
  gtk_widget_show (label39);
  gtk_frame_set_label_widget (GTK_FRAME (frame10), label39);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  follow_path = gtk_button_new_with_mnemonic (_("Follow Path"));
  gtk_widget_show (follow_path);
  gtk_fixed_put (GTK_FIXED (fixed2), follow_path, 0, 592);
  gtk_widget_set_size_request (follow_path, 120, 32);

  stop_following = gtk_button_new_with_mnemonic (_("Stop Following"));
  gtk_widget_show (stop_following);
  gtk_fixed_put (GTK_FIXED (fixed2), stop_following, 128, 592);
  gtk_widget_set_size_request (stop_following, 120, 32);

  connect_to_player = gtk_button_new_with_mnemonic (_("Show Tree"));
  gtk_widget_show (connect_to_player);
  gtk_fixed_put (GTK_FIXED (fixed2), connect_to_player, 0, 552);
  gtk_widget_set_size_request (connect_to_player, 248, 32);

  path_plan = gtk_button_new_with_mnemonic (_("Path Plan"));
  gtk_widget_show (path_plan);
  gtk_fixed_put (GTK_FIXED (fixed2), path_plan, 0, 512);
  gtk_widget_set_size_request (path_plan, 120, 32);

  frame11 = gtk_frame_new (NULL);
  gtk_widget_show (frame11);
  gtk_fixed_put (GTK_FIXED (fixed2), frame11, 0, 456);
  gtk_widget_set_size_request (frame11, 248, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (frame11), alignment11);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment11), 0, 0, 12, 0);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (alignment11), fixed3);

  simulate_radio = gtk_radio_button_new_with_mnemonic (NULL, _("Simulate/Stage"));
  gtk_widget_show (simulate_radio);
  gtk_fixed_put (GTK_FIXED (fixed3), simulate_radio, 0, 0);
  gtk_widget_set_size_request (simulate_radio, 120, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (simulate_radio), simulate_radio_group);
  simulate_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (simulate_radio));

  wheelchair_radio = gtk_radio_button_new_with_mnemonic (NULL, _("Wheelchair"));
  gtk_widget_show (wheelchair_radio);
  gtk_fixed_put (GTK_FIXED (fixed3), wheelchair_radio, 128, 0);
  gtk_widget_set_size_request (wheelchair_radio, 96, 21);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (wheelchair_radio), simulate_radio_group);
  simulate_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (wheelchair_radio));

  label47 = gtk_label_new (_("<b>Platform</b>"));
  gtk_widget_show (label47);
  gtk_frame_set_label_widget (GTK_FRAME (frame11), label47);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  generate_cspace = gtk_button_new_with_mnemonic (_("Generate Space"));
  gtk_widget_show (generate_cspace);
  gtk_fixed_put (GTK_FIXED (fixed2), generate_cspace, 128, 512);
  gtk_widget_set_size_request (generate_cspace, 120, 32);

  label13 = gtk_label_new (_("<b>Navigatoion Options</b>"));
  gtk_widget_show (label13);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label13);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window_exit),
                    NULL);
  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) cut1, "activate",
                    G_CALLBACK (on_cut1_activate),
                    NULL);
  g_signal_connect ((gpointer) copy1, "activate",
                    G_CALLBACK (on_copy1_activate),
                    NULL);
  g_signal_connect ((gpointer) paste1, "activate",
                    G_CALLBACK (on_paste1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete1, "activate",
                    G_CALLBACK (on_delete1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "configure_event",
                    G_CALLBACK (on_drawingarea1_configure_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "expose_event",
                    G_CALLBACK (on_drawingarea1_expose_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "motion_notify_event",
                    G_CALLBACK (on_drawingarea1_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea1, "button_release_event",
                    G_CALLBACK (on_drawingarea1_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) entry1, "changed",
                    G_CALLBACK (on_entry1_changed),
                    NULL);
  g_signal_connect ((gpointer) entry2, "changed",
                    G_CALLBACK (on_entry2_changed),
                    NULL);
  g_signal_connect ((gpointer) entry3, "changed",
                    G_CALLBACK (on_entry3_changed),
                    NULL);
  g_signal_connect ((gpointer) startx, "value_changed",
                    G_CALLBACK (on_startx_value_changed),
                    NULL);
  g_signal_connect ((gpointer) starty, "value_changed",
                    G_CALLBACK (on_starty_value_changed),
                    NULL);
  g_signal_connect ((gpointer) start_theta, "value_changed",
                    G_CALLBACK (on_start_theta_value_changed),
                    NULL);
  g_signal_connect ((gpointer) entry4, "changed",
                    G_CALLBACK (on_entry4_changed),
                    NULL);
  g_signal_connect ((gpointer) entry5, "changed",
                    G_CALLBACK (on_entry5_changed),
                    NULL);
  g_signal_connect ((gpointer) entry6, "changed",
                    G_CALLBACK (on_entry6_changed),
                    NULL);
  g_signal_connect ((gpointer) targetx, "value_changed",
                    G_CALLBACK (on_targetx_value_changed),
                    NULL);
  g_signal_connect ((gpointer) targety, "value_changed",
                    G_CALLBACK (on_targety_value_changed),
                    NULL);
  g_signal_connect ((gpointer) target_theta, "value_changed",
                    G_CALLBACK (on_target_theta_value_changed),
                    NULL);
  g_signal_connect ((gpointer) pixel_size, "changed",
                    G_CALLBACK (on_pixel_size_changed),
                    NULL);
  g_signal_connect ((gpointer) pixels_per_tile, "changed",
                    G_CALLBACK (on_pixels_per_tile_changed),
                    NULL);
  g_signal_connect ((gpointer) reg_grid_dist, "changed",
                    G_CALLBACK (on_reg_grid_changed),
                    NULL);
  g_signal_connect ((gpointer) nodes_connection_radius, "changed",
                    G_CALLBACK (on_dist_node_changed),
                    NULL);
  g_signal_connect ((gpointer) obstacle_radius, "changed",
                    G_CALLBACK (on_obstacle_radius_changed),
                    NULL);
  g_signal_connect ((gpointer) bridge_length, "changed",
                    G_CALLBACK (on_bridge_length_changed),
                    NULL);
  g_signal_connect ((gpointer) k_distance, "changed",
                    G_CALLBACK (on_k_distance_changed),
                    NULL);
  g_signal_connect ((gpointer) k_theta, "changed",
                    G_CALLBACK (on_k_theta_changed),
                    NULL);
  g_signal_connect ((gpointer) tracking_distance, "value_changed",
                    G_CALLBACK (on_tracking_distance_value_changed),
                    NULL);
  g_signal_connect ((gpointer) Linea_speed, "value_changed",
                    G_CALLBACK (on_Linea_speed_value_changed),
                    NULL);
  g_signal_connect ((gpointer) safety_distance, "value_changed",
                    G_CALLBACK (on_safety_distance_value_changed),
                    NULL);
  g_signal_connect ((gpointer) follow_path, "released",
                    G_CALLBACK (on_follow_path_released),
                    NULL);
  g_signal_connect ((gpointer) stop_following, "released",
                    G_CALLBACK (on_stop_following_released),
                    NULL);
  g_signal_connect ((gpointer) connect_to_player, "clicked",
                    G_CALLBACK (on_connect_to_player_clicked),
                    NULL);
  g_signal_connect ((gpointer) path_plan, "released",
                    G_CALLBACK (on_path_plan_released),
                    NULL);
  g_signal_connect ((gpointer) simulate_radio, "toggled",
                    G_CALLBACK (on_simulate_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) wheelchair_radio, "toggled",
                    G_CALLBACK (on_wheelchair_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) generate_cspace, "released",
                    G_CALLBACK (on_generate_cspace_released),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window1, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window1, menu4, "menu4");
  GLADE_HOOKUP_OBJECT (window1, new1, "new1");
  GLADE_HOOKUP_OBJECT (window1, open1, "open1");
  GLADE_HOOKUP_OBJECT (window1, save1, "save1");
  GLADE_HOOKUP_OBJECT (window1, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (window1, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (window1, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (window1, menuitem5, "menuitem5");
  GLADE_HOOKUP_OBJECT (window1, menu5, "menu5");
  GLADE_HOOKUP_OBJECT (window1, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (window1, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (window1, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (window1, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (window1, menuitem6, "menuitem6");
  GLADE_HOOKUP_OBJECT (window1, menu6, "menu6");
  GLADE_HOOKUP_OBJECT (window1, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (window1, menu7, "menu7");
  GLADE_HOOKUP_OBJECT (window1, about1, "about1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (window1, drawingarea1, "drawingarea1");
  GLADE_HOOKUP_OBJECT (window1, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window1, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (window1, label36, "label36");
  GLADE_HOOKUP_OBJECT (window1, label37, "label37");
  GLADE_HOOKUP_OBJECT (window1, label38, "label38");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (window1, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, startx, "startx");
  GLADE_HOOKUP_OBJECT (window1, starty, "starty");
  GLADE_HOOKUP_OBJECT (window1, start_theta, "start_theta");
  GLADE_HOOKUP_OBJECT (window1, label15, "label15");
  GLADE_HOOKUP_OBJECT (window1, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (window1, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, targetx, "targetx");
  GLADE_HOOKUP_OBJECT (window1, targety, "targety");
  GLADE_HOOKUP_OBJECT (window1, target_theta, "target_theta");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, frame9, "frame9");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, label31, "label31");
  GLADE_HOOKUP_OBJECT (window1, pixel_size, "pixel_size");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, pixels_per_tile, "pixels_per_tile");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, reg_grid_dist, "reg_grid_dist");
  GLADE_HOOKUP_OBJECT (window1, label34, "label34");
  GLADE_HOOKUP_OBJECT (window1, nodes_connection_radius, "nodes_connection_radius");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, label35, "label35");
  GLADE_HOOKUP_OBJECT (window1, obstacle_radius, "obstacle_radius");
  GLADE_HOOKUP_OBJECT (window1, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window1, label46, "label46");
  GLADE_HOOKUP_OBJECT (window1, bridge_length, "bridge_length");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, frame10, "frame10");
  GLADE_HOOKUP_OBJECT (window1, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, label40, "label40");
  GLADE_HOOKUP_OBJECT (window1, k_distance, "k_distance");
  GLADE_HOOKUP_OBJECT (window1, label41, "label41");
  GLADE_HOOKUP_OBJECT (window1, k_theta, "k_theta");
  GLADE_HOOKUP_OBJECT (window1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window1, label42, "label42");
  GLADE_HOOKUP_OBJECT (window1, tracking_distance, "tracking_distance");
  GLADE_HOOKUP_OBJECT (window1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window1, label43, "label43");
  GLADE_HOOKUP_OBJECT (window1, Linea_speed, "Linea_speed");
  GLADE_HOOKUP_OBJECT (window1, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window1, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window1, label45, "label45");
  GLADE_HOOKUP_OBJECT (window1, safety_distance, "safety_distance");
  GLADE_HOOKUP_OBJECT (window1, label39, "label39");
  GLADE_HOOKUP_OBJECT (window1, follow_path, "follow_path");
  GLADE_HOOKUP_OBJECT (window1, stop_following, "stop_following");
  GLADE_HOOKUP_OBJECT (window1, connect_to_player, "connect_to_player");
  GLADE_HOOKUP_OBJECT (window1, path_plan, "path_plan");
  GLADE_HOOKUP_OBJECT (window1, frame11, "frame11");
  GLADE_HOOKUP_OBJECT (window1, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, simulate_radio, "simulate_radio");
  GLADE_HOOKUP_OBJECT (window1, wheelchair_radio, "wheelchair_radio");
  GLADE_HOOKUP_OBJECT (window1, label47, "label47");
  GLADE_HOOKUP_OBJECT (window1, generate_cspace, "generate_cspace");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, statusbar1, "statusbar1");

  gtk_widget_grab_focus (window1);
  gtk_widget_grab_default (window1);
  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

