function createfigure(YMatrix1,AXBAM)
if nargin<2
    AXBAM=1;
end

maxinfo=36688;
%to get it as a percentage
YMatrix1=(YMatrix1/maxinfo)*100;
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-Nov-2007 13:42:17

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1,    'YTick',[0 12.5 25 37.5 50 62.5 75 87.5 100],...
    'XTick',[0:12],...
    'FontSize',14);

box('on');
grid('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot([0:12],YMatrix1(2:end-1));
% set(plot1(1),'DisplayName','AXBAM','marker','*');
hold on;
% plot2=plot([0:12],36688*ones([1,size(YMatrix1,2)-2]),'g')
% set(plot2(1),'DisplayName','Max Available');

% set(plot1(2),'DisplayName','Env 2','Color',[1 0 0],'LineStyle','-.');
% set(plot1(3),'DisplayName','Env 3','Color',[0 1 0]);

% Create xlabel
xlabel({'Exploration Pose Number'},'FontSize',14);

% Create ylabel
ylabel({'Information Found %'},'FontSize',14);

% Create title
if AXBAM
    title('AXBAM Case Study Exploration','FontSize',14);
else
    title('Random Pose Exploration','FontSize',14);
end

% Create legend
%  legend(axes1,'show','location','SouthEast');

