function createfigure(YMatrix1,AXBAM)
if nargin<2
    AXBAM=1;
end

    
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-Nov-2007 13:42:17

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1,...    'YTick',[1e+004 1.2e+004 1.4e+004 1.6e+004 1.8e+004 2e+004 2.2e+004 2.4e+004 2.5e+004],...
    'XTick',[0:12],...
    'FontSize',14);

box('on');
grid('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot([0:12],YMatrix1(2:end-1));
set(plot1(1),'DisplayName','AXBAM','marker','*');
hold on;
plot2=plot([0:12],36688*ones([1,size(YMatrix1,2)-2]),'g')
set(plot2(1),'DisplayName','Max Available');

% set(plot1(2),'DisplayName','Env 2','Color',[1 0 0],'LineStyle','-.');
% set(plot1(3),'DisplayName','Env 3','Color',[0 1 0]);

% Create xlabel
xlabel({'Exporation Pose Number'},'FontSize',14);

% Create ylabel
ylabel({'Information Found'},'FontSize',14);

% Create title
if AXBAM
    title('AXBAM Exploration','FontSize',14);
else
    title('Random Pose Exploration','FontSize',14);
end

% Create legend
 legend(axes1,'show','location','SouthEast');

