function special_map_area()

global RangeData PointData workspace

% load ScanforClassifier-0to-60
% workspace.spec_pnts=[];

[zeroRangeCol,zeroRangeRow]=find(RangeData<20);

%diff te pan direction
diffval=diff(RangeData,1,2);

[diffCol,diffRow]=find(diffval>workspace.inc_size*1000);

% Check that it is not a spike caused by a zero value eg +150 then -150 so
% check the sum over several values
% This also makes sure we don't included specled (varying quickly without
% any value about shadowing)
Istokeep=[];
for i=1:size(diffCol,1)
    if size(diffval,2)>(diffRow(i)+5)
        if abs(sum(diffval(diffCol(i),diffRow(i):diffRow(i)+5)))>workspace.inc_size*1000
            Istokeep=[Istokeep,i];
        end
    else
        if abs(sum(diffval(diffCol(i),diffRow(i):end)))>workspace.inc_size*1000
            Istokeep=[Istokeep,i];
        end    
    end
end

diffCol=diffCol(Istokeep);
diffRow=diffRow(Istokeep);


%special points are the diffCol,diffRow->diffRow+1 values where neither is
%a zero return (these are ignored in this section since it is too hard to
%calculate the areas of interest
ALLspec_pnts_ind=[];
for i=1:2:size(diffCol,1)
    %check if either point is from a zero range point
    if isempty(find(diffCol(i)==zeroRangeCol & zeroRangeRow==diffRow(i),1)) &&...
            isempty(find(diffCol(i)==zeroRangeCol & zeroRangeRow==diffRow(i)+1,1))
        
        radius=sqrt(sum(((PointData(diffCol(i),diffRow(i),:)-PointData(diffCol(i),diffRow(i)+1,:))/2).^2));
        %make sure the radius is not too large
        if radius>2*workspace.inc_size; radius=2*workspace.inc_size; end

        %Determine the mid point between the points with the big
        %differential
        special_point=squeeze((PointData(diffCol(i),diffRow(i),:)+PointData(diffCol(i),diffRow(i)+1,:))/2)';
        [nothing,level2]=GetImpLevInfo(special_point);
        if size(level2,1)>0 %then we know its inside level 2 at least so go on
%         workspace.spec_pnts=[workspace.spec_pnts;...
%           workspace.unknowncoords(workspace.lev2unknown(...
%           sqrt((workspace.unknowncoords(workspace.lev2unknown,1)-special_point(1)).^2+...
%                (workspace.unknowncoords(workspace.lev2unknown,2)-special_point(2)).^2+...
%                (workspace.unknowncoords(workspace.lev2unknown,3)-special_point(3)).^2)<radius),:)];   
%         workspace.spec_pnts=unique(workspace.spec_pnts,'rows');
%get the index, then use all surrounding 27 cubes
            spec_pnt_ind=round(special_point/workspace.inc_size);
            ALLspec_pnts_ind=[ALLspec_pnts_ind;...
            spec_pnt_ind(1)-1,spec_pnt_ind(2)-1,spec_pnt_ind(3)-1;...
            spec_pnt_ind(1)-1,spec_pnt_ind(2)-1,spec_pnt_ind(3);...
            spec_pnt_ind(1)-1,spec_pnt_ind(2)-1,spec_pnt_ind(3)+1;...
            spec_pnt_ind(1)-1,spec_pnt_ind(2),spec_pnt_ind(3)-1;...
            spec_pnt_ind(1)-1,spec_pnt_ind(2),spec_pnt_ind(3);...
            spec_pnt_ind(1)-1,spec_pnt_ind(2),spec_pnt_ind(3)+1;...
            spec_pnt_ind(1)-1,spec_pnt_ind(2)+1,spec_pnt_ind(3)-1;...
            spec_pnt_ind(1)-1,spec_pnt_ind(2)+1,spec_pnt_ind(3);...
            spec_pnt_ind(1)-1,spec_pnt_ind(2)+1,spec_pnt_ind(3)+1;...
            spec_pnt_ind(1),spec_pnt_ind(2)-1,spec_pnt_ind(3)-1;...
            spec_pnt_ind(1),spec_pnt_ind(2)-1,spec_pnt_ind(3);...
            spec_pnt_ind(1),spec_pnt_ind(2)-1,spec_pnt_ind(3)+1;...
            spec_pnt_ind(1),spec_pnt_ind(2),spec_pnt_ind(3)-1;...
            spec_pnt_ind(1),spec_pnt_ind(2),spec_pnt_ind(3);...
            spec_pnt_ind(1),spec_pnt_ind(2),spec_pnt_ind(3)+1;...
            spec_pnt_ind(1),spec_pnt_ind(2)+1,spec_pnt_ind(3)-1;...
            spec_pnt_ind(1),spec_pnt_ind(2)+1,spec_pnt_ind(3);...
            spec_pnt_ind(1),spec_pnt_ind(2)+1,spec_pnt_ind(3)+1;...
            spec_pnt_ind(1)+1,spec_pnt_ind(2)-1,spec_pnt_ind(3)-1;...
            spec_pnt_ind(1)+1,spec_pnt_ind(2)-1,spec_pnt_ind(3);...
            spec_pnt_ind(1)+1,spec_pnt_ind(2)-1,spec_pnt_ind(3)+1;...
            spec_pnt_ind(1)+1,spec_pnt_ind(2),spec_pnt_ind(3)-1;...
            spec_pnt_ind(1)+1,spec_pnt_ind(2),spec_pnt_ind(3);...
            spec_pnt_ind(1)+1,spec_pnt_ind(2),spec_pnt_ind(3)+1;...
            spec_pnt_ind(1)+1,spec_pnt_ind(2)+1,spec_pnt_ind(3)-1;...
            spec_pnt_ind(1)+1,spec_pnt_ind(2)+1,spec_pnt_ind(3);...
            spec_pnt_ind(1)+1,spec_pnt_ind(2)+1,spec_pnt_ind(3)+1];
        
        end
    end
end

%if we have any special points to add
if size(ALLspec_pnts_ind,1)>0
    %make it not an index anymore by real points
    workspace.spec_pnts=unique([ALLspec_pnts_ind*workspace.inc_size;workspace.spec_pnts],'rows');

    %normalise to the workspace size
    workspace.spec_pnts=round(workspace.spec_pnts/workspace.inc_size)*workspace.inc_size;
    workspace.spec_pnts=setdiff(workspace.spec_pnts,[workspace.knowncoords;workspace.indexedobsticles],'rows');
end
% plot3(workspace.spec_pnts(:,1),workspace.spec_pnts(:,2),workspace.spec_pnts(:,3),'k*');
% hold on;
% plot3(PointData(:,:,1),PointData(:,:,2),PointData(:,:,3),'g.')