//
// C++ Interface: voronoipathplanner
//
// Description:
//
//
// Author: Tarek Taha <tataha@eng.uts.edu.au>, (C) 2006
//
// Copyright: See COPYING file that comes with this distribution
//
//
#ifndef CASPLANNERVORONOIPATHPLANNER_H
#define CASPLANNERVORONOIPATHPLANNER_H

#include "astar.h"
//#include "mapskeleton.h"

namespace CasPlanner
{

/**
Generates a Path using a Map Skeleton Generated by Voronoi Diagram

	@author Tarek Taha <tataha@eng.uts.edu.au>
*/
class VoronoiPathPlanner : public Astar
{
	private :
		bool skelInitialize;
//		SSkelPtr & sskel;
	public :
		void freeResources();
		void freePath();
		void printNodeList ();
//		void setSkeleton(SSkelPtr & sskel); // Reads the map file and sets the attributes
		void buildSpace();
		void showConnections();
		void saveSearchSpace();
		bool readSpaceFromFile(const char *filename);
		bool saveSpace2File(const char *filename);
		void setStart(Pose start);
		void setEnd(Pose start);
//    	VoronoiPathPlanner(SSkelPtr & sskel);
		VoronoiPathPlanner();
   	 	~VoronoiPathPlanner();

};

}

#endif
